const { createChatCompletion } = require('./llm');
const { buildInitPrompt, buildTargetPrompt, buildIngestMergePrompt, TARGET_PROFILES } = require('./prompts');

async function transformInit(sourceContent) {
  try {
    const messages = buildInitPrompt(sourceContent);
    const result = await createChatCompletion({ messages });
    return result;
  } catch (err) {
    console.error(`[ai-rules] WARN: LLM 変換に失敗しました: ${err.message}`);
    console.error('[ai-rules] WARN: ソースをそのまま使用します。');
    return sourceContent;
  }
}

function addCursorFrontmatter(content) {
  const lines = [
    '---',
    'description: Project AI rules',
    'alwaysApply: true',
    '---',
    '',
    content.trimEnd(),
    '',
  ];
  return lines.join('\n');
}

function addOpenClawFrontmatter(content) {
  const lines = [
    '---',
    'name: personal-constitution',
    'description: Personal global AI operation rules generated by ai-rules',
    '---',
    '',
    content.trimEnd(),
    '',
  ];
  return lines.join('\n');
}

async function transformForTarget(projectContent, target) {
  const profile = TARGET_PROFILES[target];
  if (!profile) {
    return projectContent;
  }

  try {
    const messages = buildTargetPrompt(projectContent, target, profile);
    let result = await createChatCompletion({ messages });

    if (target === 'cursor') {
      result = addCursorFrontmatter(result);
    }
    if (target === 'openclaw') {
      result = addOpenClawFrontmatter(result);
    }

    return result;
  } catch (err) {
    console.error(`[ai-rules] WARN: ${target} 向け LLM 変換に失敗しました: ${err.message}`);
    console.error('[ai-rules] WARN: 既存の変換処理にフォールバックします。');
    return null;
  }
}

async function transformIngestMerge(projectContent, newContent, meta) {
  const messages = buildIngestMergePrompt(projectContent, newContent, meta);
  const result = await createChatCompletion({ messages });
  return result;
}

module.exports = {
  transformInit,
  transformForTarget,
  transformIngestMerge,
};
